use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // POSIX backend requires Unix file descriptor APIs
    if env::var_os("CARGO_CFG_UNIX").is_none() {
        panic!(
            "clickhouse-c-rs supports Unix targets only. The core block and \
             client layers are portable, but the bundled POSIX transport is \
             not; a Windows port needs a Windows chc_io backend."
        );
    }

    // Allow builds against another clickhouse-c checkout
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let chc_dir = env::var("CHC_INCLUDE_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest.join("clickhouse-c"));

    if !chc_dir.join("clickhouse.h").exists() {
        panic!(
            "clickhouse.h not found under {}. clickhouse-c is a git submodule: run \
             `git submodule update --init`. Published crate archives carry the headers \
             already, so this only bites in a fresh clone. Set CHC_INCLUDE_DIR to build \
             against a checkout elsewhere.",
            chc_dir.display()
        );
    }

    emit_upstream_revision(&manifest);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    generate_constants(&chc_dir, &out_dir);
    generate_parity_inventory(&chc_dir, &manifest, &out_dir);

    let mut build = cc::Build::new();
    build
        .file("src/wrapper.c")
        // Build structure layout probes used by tests/layout.rs
        .file("src/layout_probe.c")
        .include(&chc_dir)
        .std("c2x")
        .warnings(true)
        .extra_warnings(true)
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-function");

    // Find system codec headers before compiling wrapper
    let lz4 = cfg!(feature = "lz4").then(|| probe("liblz4", "lz4"));
    let zstd = cfg!(feature = "zstd").then(|| probe("libzstd", "zstd"));
    if lz4.is_some() {
        build.define("CHC_RS_LZ4", None);
    }
    if zstd.is_some() {
        build.define("CHC_RS_ZSTD", None);
    }
    for dir in lz4.iter().chain(zstd.iter()).flatten() {
        build.include(dir);
    }

    build.compile("clickhouse_c");

    println!("cargo:rerun-if-changed=src/wrapper.c");
    println!("cargo:rerun-if-changed=src/layout_probe.c");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=CHC_INCLUDE_DIR");
    for h in [
        "clickhouse.h",
        "clickhouse-posix-io.h",
        "clickhouse-compression.h",
        "clickhouse-client.h",
        "clickhouse-async.h",
    ] {
        let p = chc_dir.join(h);
        if p.exists() {
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }
    println!("cargo:include={}", chc_dir.display());
}

/// Locates codec headers and library with pkg-config when available.
///
/// Falls back to default compiler and linker paths. Returns additional include
/// directories for C build.
fn probe(pkg: &str, link_name: &str) -> Vec<PathBuf> {
    match pkg_config::Config::new().cargo_metadata(true).probe(pkg) {
        Ok(lib) => lib.include_paths,
        Err(e) => {
            println!(
                "cargo:warning=pkg-config could not find {pkg} ({e}); assuming -l{link_name} resolves"
            );
            println!("cargo:rustc-link-lib={link_name}");
            Vec::new()
        }
    }
}

/// Exports bundled clickhouse-c revision from `UPSTREAM` to Rust compilation.
fn emit_upstream_revision(manifest: &Path) {
    let path = manifest.join("UPSTREAM");
    let revision = fs::read_to_string(&path)
        .ok()
        .and_then(|s| {
            s.lines()
                .find_map(|l| l.split_once('=').filter(|(k, _)| k.trim() == "revision"))
                .map(|(_, v)| v.trim().to_string())
        })
        .unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=CHC_UPSTREAM_REVISION={revision}");
    println!("cargo:rerun-if-changed={}", path.display());
}

/* Generate constants from C headers */

fn generate_constants(chc_dir: &Path, out_dir: &Path) {
    let core_src = read(chc_dir, "clickhouse.h");
    let comp_src = read(chc_dir, "clickhouse-compression.h");
    let client_src = read(chc_dir, "clickhouse-client.h");

    let mut out = String::new();
    out.push_str("// Generated by build.rs from bundled clickhouse-c headers\n\n");

    // Read anonymous error code enum
    let core_enums = extract_enums(&core_src);
    let errors = core_enums
        .iter()
        .find(|(name, _)| name.is_none())
        .expect("anonymous enum (error codes) not found in clickhouse.h");
    out.push_str("// clickhouse.h: error codes (anonymous enum)\n");
    emit_enum(&mut out, &errors.1, "core::ffi::c_int");

    // Read named enums
    emit_named(
        &mut out,
        &core_enums,
        "chc_kind",
        "chc_kind",
        "clickhouse.h",
    );
    emit_named(
        &mut out,
        &core_enums,
        "chc_col_kind",
        "chc_col_kind",
        "clickhouse.h",
    );

    let comp_enums = extract_enums(&comp_src);
    emit_named(
        &mut out,
        &comp_enums,
        "chc_compression",
        "chc_compression",
        "clickhouse-compression.h",
    );

    let client_enums = extract_enums(&client_src);
    emit_named(
        &mut out,
        &client_enums,
        "chc_packet_kind",
        "chc_packet_kind",
        "clickhouse-client.h",
    );

    // Read integer macros required by Rust structures
    let msg_len = extract_define(&core_src, "CHC_ERR_MSG_LEN")
        .expect("#define CHC_ERR_MSG_LEN missing from clickhouse.h");
    out.push_str(&format!(
        "\n// clickhouse.h: #define CHC_ERR_MSG_LEN\npub const CHC_ERR_MSG_LEN: usize = {msg_len};\n"
    ));

    let revision = extract_define(&client_src, "CHC_CLIENT_DEFAULT_REVISION")
        .expect("#define CHC_CLIENT_DEFAULT_REVISION missing from clickhouse-client.h");
    out.push_str(&format!(
        "\n// clickhouse-client.h: #define CHC_CLIENT_DEFAULT_REVISION\n\
         pub const CHC_CLIENT_DEFAULT_REVISION: u64 = {revision};\n"
    ));

    fs::write(out_dir.join("sys_constants.rs"), out).expect("write sys_constants.rs");
}

fn read(dir: &Path, name: &str) -> String {
    let path = dir.join(name);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

// Optional enum tag and list of name-value pairs
type EnumBlock = (Option<String>, Vec<(String, i64)>);

fn emit_named(
    out: &mut String,
    enums: &[EnumBlock],
    enum_name: &str,
    rust_type: &str,
    source_header: &str,
) {
    let block = enums
        .iter()
        .find(|(n, _)| n.as_deref() == Some(enum_name))
        .unwrap_or_else(|| panic!("enum {enum_name} not found in {source_header}"));
    out.push_str(&format!("\n// {source_header}: enum {enum_name}\n"));
    emit_enum(out, &block.1, rust_type);
}

fn emit_enum(out: &mut String, variants: &[(String, i64)], rust_type: &str) {
    for (name, value) in variants {
        // Exclude count sentinels that are not wire values
        if name.ends_with("_COUNT") || name.ends_with("_LAST") {
            continue;
        }
        out.push_str(&format!("pub const {name}: {rust_type} = {value};\n"));
    }
}

/* Generate header and Rust binding inventories */

/// Headers represented by raw Rust bindings.
///
/// `clickhouse-openssl.h` remains available for custom I/O but is not bound.
const COVERED_HEADERS: &[&str] = &[
    "clickhouse.h",
    "clickhouse-posix-io.h",
    "clickhouse-compression.h",
    "clickhouse-client.h",
    "clickhouse-async.h",
];

/// Generates inventories compared by `src/parity.rs`.
fn generate_parity_inventory(chc_dir: &Path, manifest: &Path, out_dir: &Path) {
    let mut header_fns: Vec<String> = vec![];
    let mut header_enums: Vec<(String, String, i64)> = vec![];
    for header in COVERED_HEADERS {
        let src = read(chc_dir, header);
        let decls = declarations_of(&src);
        header_fns.extend(scan_declared_functions(&decls));
        for (tag, variants) in extract_enums(&decls) {
            let tag = tag.unwrap_or_else(|| "(anonymous)".to_string());
            for (name, value) in variants {
                header_enums.push((tag.clone(), name, value));
            }
        }
    }
    header_fns.sort();
    header_fns.dedup();
    header_enums.sort();
    header_enums.dedup();

    let sys_src = fs::read_to_string(manifest.join("src/sys.rs")).expect("read src/sys.rs");
    let mut sys_fns = scan_rust_items(&sys_src, "pub fn ", "chc_");
    sys_fns.sort();

    let mut out = String::new();
    out.push_str("// Generated by build.rs from bundled clickhouse-c headers\n\n");
    emit_str_slice(
        &mut out,
        "HEADER_FUNCTIONS",
        header_fns.iter().map(String::as_str),
    );
    emit_str_slice(
        &mut out,
        "SYS_FUNCTIONS",
        sys_fns.iter().map(String::as_str),
    );
    out.push_str("/// Enum tag, enumerator, and value from represented headers.\n");
    out.push_str("pub const HEADER_ENUMERATORS: &[(&str, &str, i64)] = &[\n");
    for (tag, name, value) in &header_enums {
        out.push_str(&format!("    ({tag:?}, {name:?}, {value}),\n"));
    }
    out.push_str("];\n");
    fs::write(out_dir.join("parity.rs"), out).expect("write parity.rs");

    println!(
        "cargo:rerun-if-changed={}",
        manifest.join("src/sys.rs").display()
    );
}

fn emit_str_slice<'a>(out: &mut String, name: &str, items: impl Iterator<Item = &'a str>) {
    out.push_str(&format!("pub const {name}: &[&str] = &[\n"));
    for item in items {
        out.push_str(&format!("    {item:?},\n"));
    }
    out.push_str("];\n\n");
}

/// Returns public declarations before `CHC_IMPLEMENTATION` guard.
fn declarations_of(src: &str) -> String {
    let src = strip_comments(src);
    match src.find("#ifdef CHC_IMPLEMENTATION") {
        Some(at) => src[..at].to_string(),
        None => src,
    }
}

/// Returns public `chc_*` function names, excluding `chc__*` internals.
fn scan_declared_functions(decls: &str) -> Vec<String> {
    let bytes = decls.as_bytes();
    let mut out = vec![];
    let mut i = 0;
    while i < bytes.len() {
        if !decls[i..].starts_with("chc_")
            || i.checked_sub(1).is_some_and(|p| is_ident_byte(bytes[p]))
        {
            i += 1;
            continue;
        }
        let start = i;
        while i < bytes.len() && is_ident_byte(bytes[i]) {
            i += 1;
        }
        let name = &decls[start..i];
        let mut j = i;
        while j < bytes.len() && bytes[j].is_ascii_whitespace() {
            j += 1;
        }
        if bytes.get(j) == Some(&b'(') && !name.starts_with("chc__") {
            out.push(name.to_string());
        }
    }
    out
}

/// Returns Rust item names following `keyword` and `prefix`.
fn scan_rust_items(src: &str, keyword: &str, prefix: &str) -> Vec<String> {
    let mut out = vec![];
    for (at, _) in src.match_indices(keyword) {
        let rest = &src[at + keyword.len()..];
        if !rest.starts_with(prefix) {
            continue;
        }
        let end = rest
            .find(|c: char| !c.is_ascii_alphanumeric() && c != '_')
            .unwrap_or(rest.len());
        out.push(rest[..end].to_string());
    }
    out
}

/* C header parsers */

fn strip_comments(src: &str) -> String {
    let bytes = src.as_bytes();
    let mut out = String::with_capacity(src.len());
    let mut i = 0;
    while i < bytes.len() {
        if i + 1 < bytes.len() && bytes[i] == b'/' && bytes[i + 1] == b'/' {
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
        } else if i + 1 < bytes.len() && bytes[i] == b'/' && bytes[i + 1] == b'*' {
            i += 2;
            while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                i += 1;
            }
            if i + 1 < bytes.len() {
                i += 2;
            }
        } else {
            out.push(bytes[i] as char);
            i += 1;
        }
    }
    out
}

fn is_ident_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_'
}

/// Parses C enums, including explicit integer values and implicit increments.
fn extract_enums(src: &str) -> Vec<EnumBlock> {
    let src = strip_comments(src);
    let bytes = src.as_bytes();
    let mut results = vec![];
    let mut i = 0;
    while i + 4 <= bytes.len() {
        if &bytes[i..i + 4] == b"enum"
            && i.checked_sub(1)
                .map(|p| !is_ident_byte(bytes[p]))
                .unwrap_or(true)
            && bytes.get(i + 4).is_none_or(|b| !is_ident_byte(*b))
        {
            // Skip enum keyword
            let mut j = i + 4;
            while j < bytes.len() && bytes[j].is_ascii_whitespace() {
                j += 1;
            }
            // Read optional enum tag
            let mut name: Option<String> = None;
            if j < bytes.len() && (bytes[j].is_ascii_alphabetic() || bytes[j] == b'_') {
                let start = j;
                while j < bytes.len() && is_ident_byte(bytes[j]) {
                    j += 1;
                }
                name = Some(src[start..j].to_string());
                while j < bytes.len() && bytes[j].is_ascii_whitespace() {
                    j += 1;
                }
            }
            if j < bytes.len() && bytes[j] == b'{' {
                let body_start = j + 1;
                // Track nesting for future header changes
                let mut depth = 1;
                let mut k = body_start;
                while k < bytes.len() && depth > 0 {
                    match bytes[k] {
                        b'{' => depth += 1,
                        b'}' => depth -= 1,
                        _ => {}
                    }
                    k += 1;
                }
                if depth == 0 {
                    let body = &src[body_start..k - 1];
                    let variants = parse_enum_body(body);
                    if !variants.is_empty() {
                        results.push((name, variants));
                    }
                    i = k;
                    continue;
                }
            }
        }
        i += 1;
    }
    results
}

fn parse_enum_body(body: &str) -> Vec<(String, i64)> {
    let mut out = vec![];
    let mut next_value: i64 = 0;
    for raw in body.split(',') {
        let raw = raw.trim();
        if raw.is_empty() {
            continue;
        }
        if let Some(eq) = raw.find('=') {
            let name = raw[..eq].trim();
            let value_str = raw[eq + 1..].trim();
            let Some(value) = parse_c_integer(value_str) else {
                continue;
            };
            out.push((name.to_string(), value));
            next_value = value + 1;
        } else {
            out.push((raw.to_string(), next_value));
            next_value += 1;
        }
    }
    out
}

fn parse_c_integer(s: &str) -> Option<i64> {
    let s = s.trim();
    let s = s.trim_end_matches(['u', 'U', 'l', 'L']);
    if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        i64::from_str_radix(hex, 16).ok()
    } else {
        s.parse().ok()
    }
}

fn extract_define(src: &str, name: &str) -> Option<i64> {
    let src = strip_comments(src);
    for line in src.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix("#define") else {
            continue;
        };
        let rest = rest.trim_start();
        let end = rest
            .find(|c: char| !c.is_ascii_alphanumeric() && c != '_')
            .unwrap_or(rest.len());
        if &rest[..end] != name {
            continue;
        }
        return parse_c_integer(rest[end..].trim_start());
    }
    None
}
